<?php

class DummyChild extends WireData implements Module {

  protected $configuration;

  public static function getModuleInfo() {
    return array(
      'title' => __('Dummy Child Module', __FILE__),
      'version' => 1, 
      'summary' => 'Just for testing',
    );
  }

  public function init()
  {
    echo "Child has been created!\n";
  }

  public function ___install()
  {
    if($this->ac)
    {
      $this->ac->attach($this, "DummyParent");
    }
  }

  public function ___uninstall()
  {
    if($this->ac)
    {
      $this->ac->detach($this, "DummyParent");
    }
  }
}
