<?php

class DummyParent extends WireData implements Module {

  protected $configuration;

  public static function getModuleInfo() {
    return array(
      'title' => __('Dummy Parent Module', __FILE__),
      'version' => 1, 
      'summary' => 'Just for testing',
    );
  }

  public function init()
  {
    echo "Parent has been called to action!\n";
    if($this->ac)
    {
      $this->ac->load($this);
    }
  }
}
